meta:
  - .github/*
  - .github/**/*
  - .gitignore
  - .security.txt
  - CODE_OF_CONDUCT.md
  - LICENSE
  - README.md
  - SECURITY.md
  
actions:
  - .github/*.yml
  - .github/**/*.yml
  - azure-pipelines/*
  - azure-pipelines/**/*
  - Dockerfile
  - docker-compose.yml
  - deployment.yaml

labels:
  - .github/labels.json

admin:
  - cdbot/cogs/admin.py

cyber:
  - cdbot/cogs/cyber.py

maths:
  - cdbot/cogs/maths.py

fun:
  - cdbot/cogs/fun.py

general:
  - cdbot/cogs/general.py

module:
  - cdbot/__init__.py
  - cdbot/__main__.py
  - cdbot/bot.py
  - cdbot/constants.py
  - cdbot/log.py
  - cdbot/data/*
  - cdbot/data/**/*
  - cdbot/resources/*
  - cdbot/resources/**/*
  - pyproject.toml
  - poetry.lock

dependencies:
  - poetry.lock
