language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  only:
    - "master"

services:
  - docker

install:
  - docker build -t cd-bot .
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker run -d -e BOT_TOKEN --name cd-bot cd-bot; fi'
  - pip install -r requirements-ci.txt

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker ps | grep cd-bot; fi'
  - python -m flake8 .

after_success:
  - bash deploy.sh

cache: pip
