language: python
python:
  - "3.6"

branches:
  only:
    - "master"

services:
  - docker

install:
  - docker build -t cd-bot .
  - docker run -d -e BOT_TOKEN --name cd-bot cd-bot
  - pip install -r requirements-ci.txt

script:
  - docker ps | grep cd-bot
  - flake8

cache: pip
