apiVersion: "v1"
kind: "Service"
metadata:
  name: "postgres"
  labels:
    app: "postgres"
spec:
  ports:
  - port: 5432
    name: "postgres"
  clusterIP: "None"
  selector:
    app: "postgres"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
      - name: "postgres"
        image: "postgres:11"
        env:
        - name: "POSTGRES_DB"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "PGDATABASE"
        - name: "POSTGRES_USER"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "PGUSER"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "PGPASSWORD"
        ports:
        - containerPort: 5432
          name: postgredb
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cyberdisc-bot"
  namespace: "default"
  labels:
    app: "cyberdisc-bot"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cyberdisc-bot"
  template:
    metadata:
      labels:
        app: "cyberdisc-bot"
    spec:
      containers:
      - name: "cyberdisc-bot"
        image: "cyberdiscovery/cdbot:latest"
        env:
        - name: "BOT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "BOT_TOKEN"
        - name: "PGHOST"
          value: "postgres"
        - name: "PGPORT"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "PGPORT"
        - name: "PGDATABASE"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "PGDATABASE"
        - name: "PGUSER"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "PGUSER"
        - name: "PGPASSWORD"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "PGPASSWORD"
        - name: "SENTRY_URL"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "SENTRY_URL"
        - name: "MATHS_TOKEN"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "MATHS_TOKEN"
