apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "cyberdisc-bot"
  namespace: "default"
  labels:
    app: "cyberdisc-bot"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cyberdisc-bot"
  template:
    metadata:
      labels:
        app: "cyberdisc-bot"
    spec:
      containers:
      - name: "cyberdisc-bot"
        image: "cyberdiscovery/cdbot:latest"
        env:
        - name: "BOT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: 'creds'
              key: 'BOT_TOKEN'
        - name: "PGHOST"
          valueFrom:
            secretKeyRef:
              name: 'creds'
              key: 'PGHOST'
        - name: "PGPORT"
          valueFrom:
            secretKeyRef:
              name: 'creds'
              key: 'PGPORT'
        - name: "PGDATABASE"
          valueFrom:
            secretKeyRef:
              name: 'creds'
              key: 'PGDATABASE'
        - name: "PGUSER"
          valueFrom:
            secretKeyRef:
              name: 'creds'
              key: 'PGUSER'
        - name: "PGPASSWORD"
          valueFrom:
            secretKeyRef:
              name: 'creds'
              key: 'PGPASSWORD'
        - name: "SENTRY_URL"
          valueFrom:
            secretKeyRef:
              name: 'creds'
              key: 'SENTRY_URL'
