---
apiVersion: v1
kind: Pod
metadata:
  name: cyberdisc-db
  labels:
    name: cyberdisc-db
spec:
  replicas: 1
  containers:
    - image: launcher.gcr.io/google/mongodb3
      name: mongo
      volumeMounts:
        - name: data
          mountPath: /data/db
          subPath: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: cyberdisc-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cyberdisc-data
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "cyberdisc-db"
  labels:
    app: "cyberdisc-db"
spec:
  ports:
  - port: 27017
    name: "cyberdisc-db"
  clusterIP: "None"
  selector:
    app: "cyberdisc-db"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cyberdisc-bot"
  namespace: "default"
  labels:
    app: "cyberdisc-bot"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cyberdisc-bot"
  template:
    metadata:
      labels:
        app: "cyberdisc-bot"
    spec:
      containers:
      - name: "cyberdisc-bot"
        image: "cyberdiscovery/cdbot:latest"
        env:
        - name: "BOT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "BOT_TOKEN"
        - name: "SENTRY_URL"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "SENTRY_URL"
