version: '3'

volumes:

  database:
    driver: local


services:

  database:
    image: postgres:11
    volumes:
      - database:/var/lib/postgresql/data

  bot:
    build: .
    links:
      - database
    environment:
      - PGHOST=database
      - PGUSER=postgres
      - PGDATABASE=postgres
      - BOT_TOKEN
      - QUOTES_BOT_ID
      - QUOTES_CHANNEL_ID
      - LOGGING_CHANNEL_ID

