[tool.poetry]
name = "cdbot"
version = "0.1.0"
description = "A Discord bot for the Cyber Discovery community."
authors = ["Cyber Discovery Community <triggerhappymods@cyberdiscoverycommunity.uk>"]
license = "MIT"

[tool.poetry.dependencies]
aiohttp = "=3.3.0"
"discord.py" = {git = "https://github.com/Rapptz/discord.py", branch = "rewrite"}
python = "^3.7"
python-dateutil = "^2.8"
asyncpg = "^0.18.3"
sentry-sdk = "^0.7.3"
Pillow = "^5.4"

[tool.poetry.dev-dependencies]
flake8 = "=3.6.0"
flake8-bandit = "=1.0.2"
flake8-bugbear = "=18.8.0"
flake8-import-order = "=0.18"
flake8-string-format = "=0.2.3"
flake8-tidy-imports = "=1.1.0"
flake8-todo = "=0.7"
safety = "=1.8.4"
dodgy = "=0.1.9"

[tool.poetry.scripts]
cdbot = "cdbot:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

