[tool.poetry]
name = "cdbot"
version = "0.1.0"
description = "A Discord bot for the Cyber Discovery community."
authors = ["Cyber Discovery Community <triggerhappymods@cyberdiscoverycommunity.uk>"]
license = "MIT"

[tool.poetry.dependencies]
aiohttp = "=3.3.0"
"discord.py" = "^1.0"
python = "^3.7"
python-dateutil = "^2.8"
asyncpg = "^0.18.3"
sentry-sdk = "^0.7.3"
Pillow = "^5.4"
gitpython = "^2.1"
aiosqlite = "^0.10.0"

[tool.poetry.dev-dependencies]
flake8 = "*"
flake8-bandit = "*"
flake8-bugbear = "*"
flake8-import-order = "*"
flake8-string-format = "*"
flake8-tidy-imports = "*"
flake8-todo = "*"
safety = "*"
dodgy = "*"
mypy = "^0.740"

[tool.poetry.scripts]
cdbot = "cdbot:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
