pr:
  autoCancel: false
  branches:
    include:
    - '*'

jobs:
- job: lint
  displayName: 'Lint'

  pool:
    vmImage: 'Ubuntu 18.04'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Set Python version'
    inputs:
      versionSpec: '3.8.x'
      addToPath: true

  - task: Cache@2
    inputs:
      key: 'python | "$(Agent.OS)" | poetry.lock'
      restoreKeys: |
        python | "$(Agent.OS)"
        python
      path:  /home/vsts/.cache/pip
      displayName: "Cache Python packages"

  - script: pip install -r requirements-ci.txt
    displayName: 'Install project using pip'

  - script: python -m flake8 .
    displayName: 'Run linter'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/flake8.xml'
      testRunTitle: 'Publish test results from flake8'

- job: build
  displayName: 'Build'
  
  pool:
    vmImage: 'Ubuntu 18.04'

  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      dockerFile: '$(System.DefaultWorkingDirectory)/Dockerfile'
      imageName: 'cyberdiscovery/cdbot:latest'

- job: validate
  displayName: Validate

  pool:
    vmImage: 'Ubuntu 18.04'

  steps:
  - script: wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
    displayName: 'Download Kubeval'

  - task: ExtractFiles@1
    displayName: 'Extract Kubeval'
    inputs:
      archiveFilePatterns: '*.tar.gz'
      destinationFolder: /tmp/kubeval

  - script: '/tmp/kubeval/kubeval deployment.yaml'
    displayName: 'Run Kubeval'
