trigger:
- master

pr: none

stages:
  - stage: Publish
    jobs:
      - job: Publish
        displayName: Publish

        pool:
          vmImage: Ubuntu 18.04

        steps:
        - task: Docker@2
          displayName: 'Publish to Docker Hub'
          inputs:
            containerRegistry: 'cdbot dockerhub'
            repository: cyberdiscovery/cdbot
            Dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
            tags: latest

        - task: Docker@2
          displayName: 'Publish to GitHub Packages'
          inputs:
            containerRegistry: 'GitHub Packages'
            repository: 'CyberDiscovery/cyberdisc-bot/cyberdisc-bot'
            tags: latest

      - job: Sentry
        displayName: Sentry

        pool:
          vmImage: Ubuntu 18.04

        steps:
          - script: curl -sL https://sentry.io/get-cli/ | bash
            displayName: 'Install Sentry CLI'
            env:
              SENTRY_AUTH_TOKEN: $(SENTRY_AUTH_TOKEN)
              SENTRY_ORG: $(SENTRY_ORG)

          - script: VERSION=$(sentry-cli releases propose-version)
            displayName: 'Set Sentry release version'
            env:
              SENTRY_AUTH_TOKEN: $(SENTRY_AUTH_TOKEN)
              SENTRY_ORG: $(SENTRY_ORG)
            
          - script: sentry-cli releases new -p cyberdisc-bot $VERSION
            displayName: 'Create new Sentry release'
            env:
              SENTRY_AUTH_TOKEN: $(SENTRY_AUTH_TOKEN)
              SENTRY_ORG: $(SENTRY_ORG)

          - script: sentry-cli releases set-commits --auto $VERSION
            displayName: 'Associate commits with Sentry release'
            env:
              SENTRY_AUTH_TOKEN: $(SENTRY_AUTH_TOKEN)
              SENTRY_ORG: $(SENTRY_ORG)
            
          - script: sentry-cli releases finalize $VERSION
            displayName: 'Finalise Sentry release'
            env:
              SENTRY_AUTH_TOKEN: $(SENTRY_AUTH_TOKEN)
              SENTRY_ORG: $(SENTRY_ORG)
  
  - stage: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy

        pool:
          vmImage: Ubuntu 18.04

        steps:
        - task: Kubernetes@1
          displayName: 'Delete Old Cluster'
          inputs:
            kubernetesServiceEndpoint: 'Bot Environment-default-1568896840810'
            command: delete
            arguments: 'deployment.extensions/cyberdisc-bot deployment.extensions/postgres'
            versionSpec: 1.15.0

        - task: Kubernetes@1
          displayName: 'Deploy to Google Kubernetes Engine'
          inputs:
            kubernetesServiceEndpoint: 'Bot Environment-default-1568896840810'
            command: apply
            useConfigurationFile: true
            configuration: '$(System.DefaultWorkingDirectory)/deployment.yaml'
            secretType: generic
            forceUpdate: false
            versionSpec: 1.15.0
